
networks:
  wanderlust_app_network:
    driver: bridge


services:
  backend:
    build: /backend
    container_name: backend
    image: wanderlust_backend:latest
    environment:
      - PORT=8000
      - FRONTEND_URL=http://localhost:8000
      - BACKEND_URL=http://backend:8000
      - ACCESS_COOKIE_MAXAGE=120000
      - ACCESS_TOKEN_EXPIRES_IN=120s
      - REFRESH_COOKIE_MAXAGE=120000
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - JWT_SECRET=70dd8b38486eee723ce2505f6db06f1ee503fde5eb06fc04687191a0ed665f3f98776902d2c89f6b993b1c579a87fedaf584c693a106f7cbf16e8b4e67e9d6df
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=your_actual_google_client_id_here
      - GOOGLE_CLIENT_SECRET=your_actual_google_client_secret_here
      - MONGODB_URI=mongodb://admin:secret123@mongo:27017/wanderlust?authSource=admin
      - REDIS_URL=redis://:redisSecret123@redis:6379
    ports:
      - 8000:8000
    depends_on:
      mongo:
        condition: service_healthy 
      redis:
        condition: service_healthy
    networks:
      - wanderlust_app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  frontend:
    build: /frontend
    image: wanderlust_frontend:latest
    environment:
      # - VITE_API_PATH="http://backend:8000"
      - VITE_API_PATH="http://localhost:8000"

    ports:
      # - 3000:80
      - 80:80
    networks:
      - wanderlust_app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      backend:
        condition: service_healthy

  mongo:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: wanderlust
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - wanderlust_app_network
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://admin:secret123@localhost:27017/admin", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--requirepass", "redisSecret123"]
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - wanderlust_app_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redisSecret123", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
volumes:
  mongo-data:
  redis-data:
      
    

    